image: gitlab.dev.ifs.hsr.ch:45023/epj/2020/pwire/pwire-frontend:latest

services:
  - mysql:5.7

variables:
  MYSQL_DATABASE: homestead
  MYSQL_ROOT_PASSWORD: secret
  DB_HOST: mysql
  DB_USERNAME: root

stages:
  - test

unit_test:
  stage: test
  script:
    - cp .env.testing .env
    - composer install
    - php artisan key:generate
    - php artisan migrate
    - vendor/bin/phpunit --coverage-text --colors=never
