image: gitlab.dev.ifs.hsr.ch:45023/epj/2020/pwire/pwire-frontend:latest

services:
  - mysql:5.7

variables:
  MYSQL_DATABASE: homestead
  MYSQL_ROOT_PASSWORD: secret
  DB_HOST: mysql
  DB_USERNAME: root

stages:
  - test
  - build
  - deploy

unit_test:
  stage: test
  script:
    - cp .env.testing .env
    - composer install
    - php artisan key:generate
    - php artisan migrate
    - vendor/bin/phpunit --coverage-text --colors=never
    - npm install --save-dev jest
    - npm test --ci --coverage

build:
  stage: build
  script:
    - composer install --optimize-autoloader --no-dev
    - npm install
    - npm run prod
  artifacts:
    paths:
    - artisan
    - laravel-echo-server.json
    - .env.example
    - composer.json
    - composer.lock
    - package.json
    - package-lock.json
    - vendor
    - storage
    - routes
    - resources
    - public
    - database
    - config
    - tests
    - app
    - bootstrap
    - server.php
    expire_in: 1 week

deploy:
  stage: deploy
  only:
    - master
  trigger: epj/2020/pwire/pwire-installer
